//
// Created by keega on 6/9/2021.
//

#ifndef STS_SEED_SEARCH_STS_CONSTANTS_H
#define STS_SEED_SEARCH_STS_CONSTANTS_H

namespace sts {

    static const char *cardNames[]{
            "ACCURACY",
            "ACROBATICS",
            "ADRENALINE",
            "AFTER_IMAGE",
            "AGGREGATE",
            "ALCHEMIZE",
            "ALL_FOR_ONE",
            "ALL_OUT_ATTACK",
            "ALPHA",
            "AMPLIFY",
            "ANGER",
            "ARMAMENTS",
            "AUTO_SHIELDS",
            "A_THOUSAND_CUTS",
            "BACKFLIP",
            "BACKSTAB",
            "BALL_LIGHTNING",
            "BANE",
            "BARRAGE",
            "BARRICADE",
            "BATTLE_HYMN",
            "BATTLE_TRANCE",
            "BEAM_CELL",
            "BERSERK",
            "BIASED_COGNITION",
            "BLADE_DANCE",
            "BLASPHEMY",
            "BLIZZARD",
            "BLOODLETTING",
            "BLOOD_FOR_BLOOD",
            "BLUDGEON",
            "BLUR",
            "BODY_SLAM",
            "BOOT_SEQUENCE",
            "BOUNCING_FLASK",
            "BOWLING_BASH",
            "BRILLIANCE",
            "BRUTALITY",
            "BUFFER",
            "BULLET_TIME",
            "BULLSEYE",
            "BURNING_PACT",
            "BURST",
            "CALCULATED_GAMBLE",
            "CALTROPS",
            "CAPACITOR",
            "CARNAGE",
            "CARVE_REALITY",
            "CATALYST",
            "CHAOS",
            "CHARGE_BATTERY",
            "CHILL",
            "CHOKE",
            "CLASH",
            "CLAW",
            "CLEAVE",
            "CLOAK_AND_DAGGER",
            "CLOTHESLINE",
            "COLD_SNAP",
            "COLLECT",
            "COMBUST",
            "COMPILE_DRIVER",
            "CONCENTRATE",
            "CONCLUDE",
            "CONJURE_BLADE",
            "CONSECRATE",
            "CONSUME",
            "COOLHEADED",
            "CORE_SURGE",
            "CORPSE_EXPLOSION",
            "CORRUPTION",
            "CREATIVE_AI",
            "CRESCENDO",
            "CRIPPLING_CLOUD",
            "CRUSH_JOINTS",
            "CUT_THROUGH_FATE",
            "DAGGER_SPRAY",
            "DAGGER_THROW",
            "DARKNESS",
            "DARK_EMBRACE",
            "DASH",
            "DEADLY_POISON",
            "DECEIVE_REALITY",
            "DEFLECT",
            "DEFRAGMENT",
            "DEMON_FORM",
            "DEUS_EX_MACHINA",
            "DEVA_FORM",
            "DEVOTION",
            "DIE_DIE_DIE",
            "DISARM",
            "DISTRACTION",
            "DODGE_AND_ROLL",
            "DOOM_AND_GLOOM",
            "DOPPELGANGER",
            "DOUBLE_ENERGY",
            "DOUBLE_TAP",
            "DROPKICK",
            "DUAL_WIELD",
            "ECHO_FORM",
            "ELECTRODYNAMICS",
            "EMPTY_BODY",
            "EMPTY_FIST",
            "EMPTY_MIND",
            "ENDLESS_AGONY",
            "ENTRENCH",
            "ENVENOM",
            "EQUILIBRIUM",
            "ESCAPE_PLAN",
            "ESTABLISHMENT",
            "EVALUATE",
            "EVISCERATE",
            "EVOLVE",
            "EXHUME",
            "EXPERTISE",
            "FASTING",
            "FEAR_NO_EVIL",
            "FEED",
            "FEEL_NO_PAIN",
            "FIEND_FIRE",
            "FINISHER",
            "FIRE_BREATHING",
            "FISSION",
            "FLAME_BARRIER",
            "FLECHETTES",
            "FLEX",
            "FLURRY_OF_BLOWS",
            "FLYING_KNEE",
            "FLYING_SLEEVES",
            "FOLLOW_UP",
            "FOOTWORK",
            "FORCE_FIELD",
            "FOREIGN_INFLUENCE",
            "FORESIGHT",
            "FTL",
            "FUSION",
            "GENETIC_ALGORITHM",
            "GHOSTLY_ARMOR",
            "GLACIER",
            "GLASS_KNIFE",
            "GO_FOR_THE_EYES",
            "GRAND_FINALE",
            "HALT",
            "HAVOC",
            "HEADBUTT",
            "HEATSINKS",
            "HEAVY_BLADE",
            "HEEL_HOOK",
            "HELLO_WORLD",
            "HEMOKINESIS",
            "HOLOGRAM",
            "HYPERBEAM",
            "IMMOLATE",
            "IMPERVIOUS",
            "INDIGNATION",
            "INFERNAL_BLADE",
            "INFINITE_BLADES",
            "INFLAME",
            "INNER_PEACE",
            "INTIMIDATE",
            "IRON_WAVE",
            "JUDGMENT",
            "JUGGERNAUT",
            "JUST_LUCKY",
            "LEAP",
            "LEG_SWEEP",
            "LESSON_LEARNED",
            "LIKE_WATER",
            "LIMIT_BREAK",
            "LOOP",
            "MACHINE_LEARNING",
            "MALAISE",
            "MASTERFUL_STAB",
            "MASTER_REALITY",
            "MEDITATE",
            "MELTER",
            "MENTAL_FORTRESS",
            "METALLICIZE",
            "METEOR_STRIKE",
            "MULTI_CAST",
            "NIGHTMARE",
            "NIRVANA",
            "NOXIOUS_FUMES",
            "OFFERING",
            "OMNISCIENCE",
            "OUTMANEUVER",
            "OVERCLOCK",
            "PERFECTED_STRIKE",
            "PERSEVERANCE",
            "PHANTASMAL_KILLER",
            "PIERCING_WAIL",
            "POISONED_STAB",
            "POMMEL_STRIKE",
            "POWER_THROUGH",
            "PRAY",
            "PREDATOR",
            "PREPARED",
            "PRESSURE_POINTS",
            "PROSTRATE",
            "PROTECT",
            "PUMMEL",
            "QUICK_SLASH",
            "RAGE",
            "RAGNAROK",
            "RAINBOW",
            "RAMPAGE",
            "REACH_HEAVEN",
            "REAPER",
            "REBOOT",
            "REBOUND",
            "RECKLESS_CHARGE",
            "RECURSION",
            "RECYCLE",
            "REFLEX",
            "REINFORCED_BODY",
            "REPROGRAM",
            "RIDDLE_WITH_HOLES",
            "RIP_AND_TEAR",
            "RUPTURE",
            "RUSHDOWN",
            "SANCTITY",
            "SANDS_OF_TIME",
            "SASH_WHIP",
            "SCRAPE",
            "SCRAWL",
            "SEARING_BLOW",
            "SECOND_WIND",
            "SEEING_RED",
            "SEEK",
            "SELF_REPAIR",
            "SENTINEL",
            "SETUP",
            "SEVER_SOUL",
            "SHOCKWAVE",
            "SHRUG_IT_OFF",
            "SIGNATURE_MOVE",
            "SIMMERING_FURY",
            "SKEWER",
            "SKIM",
            "SLICE",
            "SNEAKY_STRIKE",
            "SPIRIT_SHIELD",
            "SPOT_WEAKNESS",
            "STACK",
            "STATIC_DISCHARGE",
            "STEAM_BARRIER",
            "STORM",
            "STORM_OF_STEEL",
            "STREAMLINE",
            "STUDY",
            "SUCKER_PUNCH",
            "SUNDER",
            "SWEEPING_BEAM",
            "SWIVEL",
            "SWORD_BOOMERANG",
            "TACTICIAN",
            "TALK_TO_THE_HAND",
            "TANTRUM",
            "TEMPEST",
            "TERROR",
            "THIRD_EYE",
            "THUNDERCLAP",
            "THUNDER_STRIKE",
            "TOOLS_OF_THE_TRADE",
            "TRANQUILITY",
            "TRUE_GRIT",
            "TURBO",
            "TWIN_STRIKE",
            "UNLOAD",
            "UPPERCUT",
            "VAULT",
            "WALLOP",
            "WARCRY",
            "WAVE_OF_THE_HAND",
            "WEAVE",
            "WELL_LAID_PLANS",
            "WHEEL_KICK",
            "WHIRLWIND",
            "WHITE_NOISE",
            "WILD_STRIKE",
            "WINDMILL_STRIKE",
            "WISH",
            "WORSHIP",
            "WRAITH_FORM",
            "WREATH_OF_FLAME",
    };

    static const char *normalCardNames[]{
            "Accuracy",
            "Acrobatics",
            "Adrenaline",
            "After Image",
            "Aggregate",
            "Alchemize",
            "All for One",
            "All-Out Attack",
            "Alpha",
            "Amplify",
            "Anger",
            "Armaments",
            "Auto-Shields",
            "A Thousand Cuts",
            "Backflip",
            "Backstab",
            "Ball Lightning",
            "Bane",
            "Barrage",
            "Barricade",
            "Battle Hymn",
            "Battle Trance",
            "Beam Cell",
            "Berserk",
            "Biased Cognition",
            "Blade Dance",
            "Blasphemy",
            "Blizzard",
            "Blood for Blood",
            "Bloodletting",
            "Bludgeon",
            "Blur",
            "Body Slam",
            "Boot Sequence",
            "Bouncing Flask",
            "Bowling Bash",
            "Brilliance",
            "Brutality",
            "Buffer",
            "Bullet Time",
            "Bullseye",
            "Burning Pact",
            "Burst",
            "Calculated Gamble",
            "Caltrops",
            "Capacitor",
            "Carnage",
            "Carve Reality",
            "Catalyst",
            "Chaos",
            "Charge Battery",
            "Chill",
            "Choke",
            "Clash",
            "Claw",
            "Cleave",
            "Cloak and Dagger",
            "Clothesline",
            "Cold Snap",
            "Collect",
            "Combust",
            "Compile Driver",
            "Concentrate",
            "Conclude",
            "Conjure Blade",
            "Consecrate",
            "Consume",
            "Coolheaded",
            "Core Surge",
            "Corpse Explosion",
            "Corruption",
            "Creative AI",
            "Crescendo",
            "Crippling Cloud",
            "Crush Joints",
            "Cut Through Fate",
            "Dagger Spray",
            "Dagger Throw",
            "Dark Embrace",
            "Darkness",
            "Dash",
            "Deadly Poison",
            "Deceive Reality",
            "Deflect",
            "Defragment",
            "Demon Form",
            "Deus Ex Machina",
            "Deva Form",
            "Devotion",
            "Die Die Die",
            "Disarm",
            "Distraction",
            "Dodge and Roll",
            "Doom and Gloom",
            "Doppelganger",
            "Double Energy",
            "Double Tap",
            "Dropkick",
            "Dual Wield",
            "Echo Form",
            "Electrodynamics",
            "Empty Body",
            "Empty Fist",
            "Empty Mind",
            "Endless Agony",
            "Entrench",
            "Envenom",
            "Equilibrium",
            "Escape Plan",
            "Establishment",
            "Evaluate",
            "Eviscerate",
            "Evolve",
            "Exhume",
            "Expertise",
            "Fasting",
            "Fear No Evil",
            "Feed",
            "Feel No Pain",
            "Fiend Fire",
            "Finisher",
            "Fire Breathing",
            "Fission",
            "Flame Barrier",
            "Flechettes",
            "Flex",
            "Flurry of Blows",
            "Flying Knee",
            "Flying Sleeves",
            "Follow-Up",
            "Footwork",
            "Force Field",
            "Foreign Influence",
            "Foresight",
            "FTL",
            "Fusion",
            "Genetic Algorithm",
            "Ghostly Armor",
            "Glacier",
            "Glass Knife",
            "Go for the Eyes",
            "Grand Finale",
            "Halt",
            "Havoc",
            "Headbutt",
            "Heatsinks",
            "Heavy Blade",
            "Heel Hook",
            "Hello World",
            "Hemokinesis",
            "Hologram",
            "Hyperbeam",
            "Immolate",
            "Impervious",
            "Indignation",
            "Infernal Blade",
            "Infinite Blades",
            "Inflame",
            "Inner Peace",
            "Intimidate",
            "Iron Wave",
            "Judgment",
            "Juggernaut",
            "Just Lucky",
            "Leap",
            "Leg Sweep",
            "Lesson Learned",
            "Like Water",
            "Limit Break",
            "Loop",
            "Machine Learning",
            "Malaise",
            "Master Reality",
            "Masterful Stab",
            "Meditate",
            "Melter",
            "Mental Fortress",
            "Metallicize",
            "Meteor Strike",
            "Multi-Cast",
            "Nightmare",
            "Nirvana",
            "Noxious Fumes",
            "Offering",
            "Omniscience",
            "Outmaneuver",
            "Overclock",
            "Perfected Strike",
            "Perseverance",
            "Phantasmal Killer",
            "Piercing Wail",
            "Poisoned Stab",
            "Pommel Strike",
            "Power Through",
            "Pray",
            "Predator",
            "Prepared",
            "Pressure Points",
            "Prostrate",
            "Protect",
            "Pummel",
            "Quick Slash",
            "Rage",
            "Ragnarok",
            "Rainbow",
            "Rampage",
            "Reach Heaven",
            "Reaper",
            "Reboot",
            "Rebound",
            "Reckless Charge",
            "Recursion",
            "Recycle",
            "Reflex",
            "Reinforced Body",
            "Reprogram",
            "Riddle with Holes",
            "Rip and Tear",
            "Rupture",
            "Rushdown",
            "Sanctity",
            "Sands of Time",
            "Sash Whip",
            "Scrape",
            "Scrawl",
            "Searing Blow",
            "Second Wind",
            "Seeing Red",
            "Seek",
            "Self Repair",
            "Sentinel",
            "Setup",
            "Sever Soul",
            "Shockwave",
            "Shrug It Off",
            "Signature Move",
            "Simmering Fury",
            "Skewer",
            "Skim",
            "Slice",
            "Sneaky Strike",
            "Spirit Shield",
            "Spot Weakness",
            "Stack",
            "Static Discharge",
            "Steam Barrier",
            "Storm",
            "Storm of Steel",
            "Streamline",
            "Study",
            "Sucker Punch",
            "Sunder",
            "Sweeping Beam",
            "Swivel",
            "Sword Boomerang",
            "Tactician",
            "Talk to the Hand",
            "Tantrum",
            "Tempest",
            "Terror",
            "Third Eye",
            "Thunderclap",
            "Thunder Strike",
            "Tools of the Trade",
            "Tranquility",
            "True Grit",
            "TURBO",
            "Twin Strike",
            "Unload",
            "Uppercut",
            "Vault",
            "Wallop",
            "Warcry",
            "Wave of the Hand",
            "Weave",
            "Well-Laid Plans",
            "Wheel Kick",
            "Whirlwind",
            "White Noise",
            "Wild Strike",
            "Windmill Strike",
            "Wish",
            "Worship",
            "Wraith Form",
            "Wreath of Flame",
    };

    enum class Card {
        ACCURACY=0,
        ACROBATICS,
        ADRENALINE,
        AFTER_IMAGE,
        AGGREGATE,
        ALCHEMIZE,
        ALL_FOR_ONE,
        ALL_OUT_ATTACK,
        ALPHA,
        AMPLIFY,
        ANGER,
        ARMAMENTS,
        AUTO_SHIELDS,
        A_THOUSAND_CUTS,
        BACKFLIP,
        BACKSTAB,
        BALL_LIGHTNING,
        BANE,
        BARRAGE,
        BARRICADE,
        BATTLE_HYMN,
        BATTLE_TRANCE,
        BEAM_CELL,
        BERSERK,
        BIASED_COGNITION,
        BLADE_DANCE,
        BLASPHEMY,
        BLIZZARD,
        BLOODLETTING,
        BLOOD_FOR_BLOOD,
        BLUDGEON,
        BLUR,
        BODY_SLAM,
        BOOT_SEQUENCE,
        BOUNCING_FLASK,
        BOWLING_BASH,
        BRILLIANCE,
        BRUTALITY,
        BUFFER,
        BULLET_TIME,
        BULLSEYE,
        BURNING_PACT,
        BURST,
        CALCULATED_GAMBLE,
        CALTROPS,
        CAPACITOR,
        CARNAGE,
        CARVE_REALITY,
        CATALYST,
        CHAOS,
        CHARGE_BATTERY,
        CHILL,
        CHOKE,
        CLASH,
        CLAW,
        CLEAVE,
        CLOAK_AND_DAGGER,
        CLOTHESLINE,
        COLD_SNAP,
        COLLECT,
        COMBUST,
        COMPILE_DRIVER,
        CONCENTRATE,
        CONCLUDE,
        CONJURE_BLADE,
        CONSECRATE,
        CONSUME,
        COOLHEADED,
        CORE_SURGE,
        CORPSE_EXPLOSION,
        CORRUPTION,
        CREATIVE_AI,
        CRESCENDO,
        CRIPPLING_CLOUD,
        CRUSH_JOINTS,
        CUT_THROUGH_FATE,
        DAGGER_SPRAY,
        DAGGER_THROW,
        DARKNESS,
        DARK_EMBRACE,
        DASH,
        DEADLY_POISON,
        DECEIVE_REALITY,
        DEFLECT,
        DEFRAGMENT,
        DEMON_FORM,
        DEUS_EX_MACHINA,
        DEVA_FORM,
        DEVOTION,
        DIE_DIE_DIE,
        DISARM,
        DISTRACTION,
        DODGE_AND_ROLL,
        DOOM_AND_GLOOM,
        DOPPELGANGER,
        DOUBLE_ENERGY,
        DOUBLE_TAP,
        DROPKICK,
        DUAL_WIELD,
        ECHO_FORM,
        ELECTRODYNAMICS,
        EMPTY_BODY,
        EMPTY_FIST,
        EMPTY_MIND,
        ENDLESS_AGONY,
        ENTRENCH,
        ENVENOM,
        EQUILIBRIUM,
        ESCAPE_PLAN,
        ESTABLISHMENT,
        EVALUATE,
        EVISCERATE,
        EVOLVE,
        EXHUME,
        EXPERTISE,
        FASTING,
        FEAR_NO_EVIL,
        FEED,
        FEEL_NO_PAIN,
        FIEND_FIRE,
        FINISHER,
        FIRE_BREATHING,
        FISSION,
        FLAME_BARRIER,
        FLECHETTES,
        FLEX,
        FLURRY_OF_BLOWS,
        FLYING_KNEE,
        FLYING_SLEEVES,
        FOLLOW_UP,
        FOOTWORK,
        FORCE_FIELD,
        FOREIGN_INFLUENCE,
        FORESIGHT,
        FTL,
        FUSION,
        GENETIC_ALGORITHM,
        GHOSTLY_ARMOR,
        GLACIER,
        GLASS_KNIFE,
        GO_FOR_THE_EYES,
        GRAND_FINALE,
        HALT,
        HAVOC,
        HEADBUTT,
        HEATSINKS,
        HEAVY_BLADE,
        HEEL_HOOK,
        HELLO_WORLD,
        HEMOKINESIS,
        HOLOGRAM,
        HYPERBEAM,
        IMMOLATE,
        IMPERVIOUS,
        INDIGNATION,
        INFERNAL_BLADE,
        INFINITE_BLADES,
        INFLAME,
        INNER_PEACE,
        INTIMIDATE,
        IRON_WAVE,
        JUDGMENT,
        JUGGERNAUT,
        JUST_LUCKY,
        LEAP,
        LEG_SWEEP,
        LESSON_LEARNED,
        LIKE_WATER,
        LIMIT_BREAK,
        LOOP,
        MACHINE_LEARNING,
        MALAISE,
        MASTERFUL_STAB,
        MASTER_REALITY,
        MEDITATE,
        MELTER,
        MENTAL_FORTRESS,
        METALLICIZE,
        METEOR_STRIKE,
        MULTI_CAST,
        NIGHTMARE,
        NIRVANA,
        NOXIOUS_FUMES,
        OFFERING,
        OMNISCIENCE,
        OUTMANEUVER,
        OVERCLOCK,
        PERFECTED_STRIKE,
        PERSEVERANCE,
        PHANTASMAL_KILLER,
        PIERCING_WAIL,
        POISONED_STAB,
        POMMEL_STRIKE,
        POWER_THROUGH,
        PRAY,
        PREDATOR,
        PREPARED,
        PRESSURE_POINTS,
        PROSTRATE,
        PROTECT,
        PUMMEL,
        QUICK_SLASH,
        RAGE,
        RAGNAROK,
        RAINBOW,
        RAMPAGE,
        REACH_HEAVEN,
        REAPER,
        REBOOT,
        REBOUND,
        RECKLESS_CHARGE,
        RECURSION,
        RECYCLE,
        REFLEX,
        REINFORCED_BODY,
        REPROGRAM,
        RIDDLE_WITH_HOLES,
        RIP_AND_TEAR,
        RUPTURE,
        RUSHDOWN,
        SANCTITY,
        SANDS_OF_TIME,
        SASH_WHIP,
        SCRAPE,
        SCRAWL,
        SEARING_BLOW,
        SECOND_WIND,
        SEEING_RED,
        SEEK,
        SELF_REPAIR,
        SENTINEL,
        SETUP,
        SEVER_SOUL,
        SHOCKWAVE,
        SHRUG_IT_OFF,
        SIGNATURE_MOVE,
        SIMMERING_FURY,
        SKEWER,
        SKIM,
        SLICE,
        SNEAKY_STRIKE,
        SPIRIT_SHIELD,
        SPOT_WEAKNESS,
        STACK,
        STATIC_DISCHARGE,
        STEAM_BARRIER,
        STORM,
        STORM_OF_STEEL,
        STREAMLINE,
        STUDY,
        SUCKER_PUNCH,
        SUNDER,
        SWEEPING_BEAM,
        SWIVEL,
        SWORD_BOOMERANG,
        TACTICIAN,
        TALK_TO_THE_HAND,
        TANTRUM,
        TEMPEST,
        TERROR,
        THIRD_EYE,
        THUNDERCLAP,
        THUNDER_STRIKE,
        TOOLS_OF_THE_TRADE,
        TRANQUILITY,
        TRUE_GRIT,
        TURBO,
        TWIN_STRIKE,
        UNLOAD,
        UPPERCUT,
        VAULT,
        WALLOP,
        WARCRY,
        WAVE_OF_THE_HAND,
        WEAVE,
        WELL_LAID_PLANS,
        WHEEL_KICK,
        WHIRLWIND,
        WHITE_NOISE,
        WILD_STRIKE,
        WINDMILL_STRIKE,
        WISH,
        WORSHIP,
        WRAITH_FORM,
        WREATH_OF_FLAME,
    };

    enum Relic {
        AKABEKO=0,
        ANCHOR,
        ANCIENT_TEA_SET,
        ART_OF_WAR,
        ASTROLABE,
        BAG_OF_MARBLES,
        BAG_OF_PREPARATION,
        BIRDFACED_URN,
        BLACK_BLOOD,
        BLACK_STAR,
        BLOODY_IDOL,
        BLOOD_VIAL,
        BLUE_CANDLE,
        BOTTLED_FLAME,
        BOTTLED_LIGHTNING,
        BOTTLED_TORNADO,
        BRIMSTONE,
        BRONZE_SCALES,
        BURNING_BLOOD,
        BUSTED_CROWN,
        CALIPERS,
        CALLING_BELL,
        CAPTAINS_WHEEL,
        CAULDRON,
        CENTENNIAL_PUZZLE,
        CERAMIC_FISH,
        CHAMPION_BELT,
        CHARONS_ASHES,
        CHEMICAL_X,
        CLOAK_CLASP,
        CLOCKWORK_SOUVENIR,
        COFFEE_DRIPPER,
        CRACKED_CORE,
        CULTIST_HEADPIECE,
        CURSED_KEY,
        DAMARU,
        DARKSTONE_PERIAPT,
        DATA_DISK,
        DEAD_BRANCH,
        DOLLYS_MIRROR,
        DREAM_CATCHER,
        DUALITY,
        DUVU_DOLL,
        ECTOPLASM,
        EMOTION_CHIP,
        EMPTY_CAGE,
        ENCHIRIDION,
        ETERNAL_FEATHER,
        FACE_OF_CLERIC,
        FOSSILIZED_HELIX,
        FROZEN_CORE,
        FROZEN_EGG,
        FROZEN_EYE,
        FUSION_HAMMER,
        GAMBLING_CHIP,
        GINGER,
        GIRYA,
        GOLDEN_EYE,
        GOLDEN_IDOL,
        GOLDPLATED_CABLES,
        GREMLIN_HORN,
        GREMLIN_VISAGE,
        HAND_DRILL,
        HAPPY_FLOWER,
        HOLY_WATER,
        HORN_CLEAT,
        HOVERING_KITE,
        ICE_CREAM,
        INCENSE_BURNER,
        INK_BOTTLE,
        INSERTER,
        JUZU_BRACELET,
        KUNAI,
        LANTERN,
        LEES_WAFFLE,
        LETTER_OPENER,
        LIZARD_TAIL,
        MAGIC_FLOWER,
        MANGO,
        MARK_OF_PAIN,
        MARK_OF_THE_BLOOM,
        MATRYOSHKA,
        MAW_BANK,
        MEAL_TICKET,
        MEAT_ON_THE_BONE,
        MEDICAL_KIT,
        MELANGE,
        MEMBERSHIP_CARD,
        MERCURY_HOURGLASS,
        MOLTEN_EGG,
        MUMMIFIED_HAND,
        MUTAGENIC_STRENGTH,
        NECRONOMICON,
        NEOWS_LAMENT,
        NILRYS_CODEX,
        NINJA_SCROLL,
        NLOTHS_GIFT,
        NLOTHS_HUNGRY_FACE,
        NUCLEAR_BATTERY,
        NUNCHAKU,
        ODDLY_SMOOTH_STONE,
        ODD_MUSHROOM,
        OLD_COIN,
        OMAMORI,
        ORANGE_PELLETS,
        ORICHALCUM,
        ORNAMENTAL_FAN,
        ORRERY,
        PANDORAS_BOX,
        PANTOGRAPH,
        PAPER_KRANE,
        PAPER_PHROG,
        PEACE_PIPE,
        PEAR,
        PEN_NIB,
        PHILOSOPHERS_STONE,
        POCKETWATCH,
        POTION_BELT,
        PRAYER_WHEEL,
        PRESERVED_INSECT,
        PRISMATIC_SHARD,
        PURE_WATER,
        QUESTION_CARD,
        RED_MASK,
        RED_SKULL,
        REGAL_PILLOW,
        RING_OF_THE_SERPENT,
        RING_OF_THE_SNAKE,
        RUNIC_CAPACITOR,
        RUNIC_CUBE,
        RUNIC_DOME,
        RUNIC_PYRAMID,
        SACRED_BARK,
        SELFFORMING_CLAY,
        SHOVEL,
        SHURIKEN,
        SINGING_BOWL,
        SLAVERS_COLLAR,
        SLING_OF_COURAGE,
        SMILING_MASK,
        SNECKO_EYE,
        SNECKO_SKULL,
        SOZU,
        SPIRIT_POOP,
        SSSERPENT_HEAD,
        STONE_CALENDAR,
        STRANGE_SPOON,
        STRAWBERRY,
        STRIKE_DUMMY,
        SUNDIAL,
        SYMBIOTIC_VIRUS,
        TEARDROP_LOCKET,
        THE_ABACUS,
        THE_BOOT,
        THE_COURIER,
        THE_SPECIMEN,
        THREAD_AND_NEEDLE,
        TINGSHA,
        TINY_CHEST,
        TINY_HOUSE,
        TOOLBOX,
        TORII,
        TOUGH_BANDAGES,
        TOXIC_EGG,
        TOY_ORNITHOPTER,
        TUNGSTEN_ROD,
        TURNIP,
        TWISTED_FUNNEL,
        UNCEASING_TOP,
        VAJRA,
        VELVET_CHOKER,
        VIOLET_LOTUS,
        WARPED_TONGS,
        WAR_PAINT,
        WHETSTONE,
        WHITE_BEAST_STATUE,
        WING_BOOTS,
        WRIST_BLADE,
    };

    enum class CharacterClass {
        IRONCLAD,
        SILENT,
        DEFECT,
        WATCHER
    };

    constexpr int SMALL_CHEST_CHANCE = 50;
    constexpr int MEDIUM_CHEST_CHANCE = 33;
    constexpr int LARGE_CHEST_CHANCE = 17;
    constexpr int COMMON_RELIC_CHANCE = 50;
    constexpr int UNCOMMON_RELIC_CHANCE = 33;
    constexpr int RARE_RELIC_CHANCE = 17;

}


#endif //STS_SEED_SEARCH_STS_CONSTANTS_H
